import Link from "next/link";
import { ApyCalculatorTool } from "@/components/apy-calculator-tool";

export default function Home() {
  return (
    <>
      <section className="hero">
        <div>
          <p className="label">Free savings growth tool</p>
          <h1>Estimate APY growth, compound interest, and future balance in seconds.</h1>
          <p>
            Use this free APY calculator to project how a savings account, CD, or investment balance can grow over time.
            Adjust your starting deposit, annual percentage yield, monthly contributions, and compounding frequency to compare outcomes fast.
          </p>
          <div className="hero-actions">
            <a className="button" href="#apy-tool">Start calculating</a>
            <Link className="button-secondary" href="/about">Learn how APY works</Link>
          </div>
        </div>
        <div className="stat-grid">
          <article className="card">
            <h2>Future balance estimate</h2>
            <p>See the projected ending balance after compound growth and recurring deposits.</p>
          </article>
          <article className="card">
            <h2>Interest earned breakdown</h2>
            <p>Separate your own contributions from the interest generated by the APY.</p>
          </article>
          <article className="card">
            <h2>Compounding comparison</h2>
            <p>Test monthly, quarterly, daily, or annual compounding to understand yield differences.</p>
          </article>
        </div>
      </section>

      <div id="apy-tool">
        <ApyCalculatorTool />
      </div>

      <section className="info-grid section">
        <article className="card">
          <h2>What is APY?</h2>
          <p>
            APY means annual percentage yield. It reflects the yearly return on your money after taking compound interest into account.
          </p>
        </article>
        <article className="card">
          <h2>Why use an APY calculator?</h2>
          <p>
            A quick APY calculator helps you compare savings options, estimate future value, and plan recurring contributions without using a spreadsheet.
          </p>
        </article>
        <article className="card">
          <h2>Works for common savings scenarios</h2>
          <p>
            Use it for high-yield savings accounts, certificates of deposit, emergency funds, and other compound-growth balances.
          </p>
        </article>
      </section>

      <section className="faq section">
        <h2>APY calculator FAQ</h2>
        <div className="faq-grid">
          <article>
            <h3>What is the difference between APY and APR?</h3>
            <p>APY includes the effect of compounding, while APR usually describes a simple annual rate without that compounding effect.</p>
          </article>
          <article>
            <h3>Do monthly contributions increase the ending balance?</h3>
            <p>Yes. Recurring contributions can significantly increase the future balance because each deposit has time to earn interest too.</p>
          </article>
          <article>
            <h3>Can I use this for a high-yield savings account?</h3>
            <p>Yes. This calculator is designed for savings-style balances where APY and compounding frequency are the main inputs.</p>
          </article>
        </div>
      </section>
    </>
  );
}
